on:
    workflow_call:
      inputs:
        image_tag:
          required: true
          type: string
jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        
        run : echo "${GITHUB_REPOSITORY}"

      - name: print out bass ref
        
        run: echo "${GITHUB_BASE_REF}"

      - name: print out bass ref
        
        run: echo "${GITHUB_REF}"

      - name: print out bass branch
        
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "This check ran ${GITHUB_REF##*/}"
          else
            echo "else block ran" 
          fi
        

